apiVersion: apps/v1
kind: Deployment
metadata:
  name:  psql-db
  namespace: default
  labels:
    app:  psql-db
spec:
  selector:
    matchLabels:
      app: psql-db
  replicas: 1
  template:
    metadata:
      labels:
        app:  psql-db
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name:  psql-db
        image: incept1on999/web_pag:db
        imagePullPolicy: Always
        ports:
        - containerPort: 5432 
          name:  psql-db
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes: 
        - name: db-storage
          persistentVolumeClaim: 
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
  namespace: default
spec:
  selector:
    app: psql-db
  type: ClusterIP
  ports:
  - name: psql-service
    protocol: TCP
    port: 5432
    targetPort: 5432