apiVersion: apps/v1
kind: Deployment
metadata:
  name:  front-depl
  namespace: default
  labels:
    app:  front-depl
spec:
  selector:
    matchLabels:
      app: front-depl
  replicas: 1
  template:
    metadata:
      labels:
        app:  front-depl
    spec:
      containers:
      - name:  front-depl
        image:  incept1on999/web_pag:front
        imagePullPolicy: Always
        ports:
        - containerPort:  8080
          name:  front-depl
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: default
spec:
  selector:
    app: front-depl
  #type: ClusterIP
  type: NodePort
  ports:
  - name: front-service
    protocol: TCP
    port: 8080
    targetPort: 8080 
    nodePort: 30001