- name: Install and configure Apache as a reverse proxy
  hosts: loadbalancer
  become: true
  tasks:
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: true

    - name: Disable default Apache sites
      ansible.builtin.command: a2dissite 000-default.conf
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf
      notify: Restart apache2

    - name: Enable required Apache modules
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - rewrite
        - proxy
        - proxy_http
        - proxy_balancer
        - lbmethod_byrequests
      notify: Restart apache2

    - name: Deploy Apache proxy configuration
      ansible.builtin.copy:
        src: ../configs/apache.conf
        dest: /etc/apache2/sites-available/apache.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart apache2

    - name: Enable Apache proxy site
      ansible.builtin.command: a2ensite apache.conf
      notify: Restart apache2
      changed_when: false

  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
