- name: Configure NGINX and disable Apache
  hosts: loadbalancer
  become: true
  tasks:

    - name: Stop and disable Apache (Debian/Ubuntu) # noqa: ignore-errors
      ansible.builtin.service:
        name: apache2
        state: stopped
        enabled: true
      ignore_errors: true

    - name: Install NGINX (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"


    - name: Deploy NGINX configuration # noqa: risky-file-permissions
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://192.168.50.6:30001/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /students {
                  proxy_pass http://192.168.50.6:30000/students;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              error_log /var/log/nginx/error.log;
              access_log /var/log/nginx/access.log combined;
          }
      notify: Restart NGINX

    - name: Ensure NGINX is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted
