version: '3.8'

services:
  web-pag-api:
    build:
      context: ./api
    environment:
      - DATABASE_URL=postgresql://paguser:2143658790ADM+@web-pag-db/pagdb
      # the link for api-secret in k8s different from this
    depends_on:
      - web-pag-db
  
  web-pag-db:
    build:
      context: ./db
    volumes:
      - pg_data:/var/lib/postgresql/data 

  web-pag-frontend:
    build:
      context: ./frontend
      args:
        URL_FOR_CONNECT_TO_API: "http://188.243.207.170:7701" 
  
  web-pag-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-pag-frontend
      - web-pag-api
    ports:
      - "80:80"

volumes:
  pg_data:  