apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: "cG9zdGdyZXNxbDovL3BhZ3VzZXI6MjE0MzY1ODc5MEFETStAcHNxbC1zZXJ2aWNlL3BhZ2Ri"
  # postgresql://paguser:2143658790ADM+@psql-service/pagdb