apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem  
  resources:
    requests:
      storage: 5Gi
  volumeName: db-pv
  storageClassName: ""  
