apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem  
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  
  nfs:
    path: /mnt/sharedir
    server: 172.27.33.12
