name: Deploy to Kubernetes

on:
  workflow_run:
    workflows:
      - Build the app
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest  # Use the latest version of kubectl

      - name: Authenticate with Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment api --insecure-skip-tls-verify
          kubectl rollout restart deployment front-depl --insecure-skip-tls-verify
          kubectl rollout restart deployment psql-db --insecure-skip-tls-verify

      - name: Verify Deployment Status
        run: kubectl get pods -o wide
